# Generated by Django 4.2.4 on 2023-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Ссылка на hh.ru')),
                ('vacancy', models.CharField(blank=True, max_length=500, null=True, verbose_name='Вакансия')),
                ('gender', models.CharField(blank=True, max_length=500, null=True, verbose_name='Гендер')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город проживания')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название компании')),
                ('work_in_real_time', models.CharField(blank=True, max_length=600, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=500, null=True, verbose_name='Общий опыт работы')),
                ('birthday', models.CharField(blank=True, max_length=100, null=True, verbose_name='День рождения')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('education', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Образование')),
                ('photo_link', models.URLField(blank=True, max_length=5000, null=True, verbose_name='Ссылка на фото')),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
