# Generated by Django 4.2.4 on 2023-08-21 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='email')),
                ('password', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorization_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='authorization_code_for_api')),
                ('access_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='access_token_for_api')),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='refresh_token_for_api')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions', to='auth.permission', verbose_name='Разрешения пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
